<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"绘画管理",
                        "menuJump":"列表",
                        "tableName":"huihua"
                    }
                ],
                "menu":"绘画管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"文学管理",
                        "menuJump":"列表",
                        "tableName":"wenxue"
                    }
                ],
                "menu":"文学管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"舞蹈管理",
                        "menuJump":"列表",
                        "tableName":"wudao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"舞蹈收藏管理",
                        "menuJump":"列表",
                        "tableName":"wudaoCollection"
                    }
                ],
                "menu":"舞蹈管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"音乐管理",
                        "menuJump":"列表",
                        "tableName":"yinyue"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"音乐收藏管理",
                        "menuJump":"列表",
                        "tableName":"yinyueCollection"
                    }
                ],
                "menu":"音乐管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"单页数据管理",
                        "menuJump":"列表",
                        "tableName":"singleSeach"
                    }
                ],
                "menu":"单页数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
            
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"绘画管理",
                        "menuJump":"列表",
                        "tableName":"huihua"
                    }
                ],
                "menu":"绘画管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"文学管理",
                        "menuJump":"列表",
                        "tableName":"wenxue"
                    }
                ],
                "menu":"文学管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"舞蹈管理",
                        "menuJump":"列表",
                        "tableName":"wudao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"舞蹈收藏管理",
                        "menuJump":"列表",
                        "tableName":"wudaoCollection"
                    }
                ],
                "menu":"舞蹈管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"音乐管理",
                        "menuJump":"列表",
                        "tableName":"yinyue"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"音乐收藏管理",
                        "menuJump":"列表",
                        "tableName":"yinyueCollection"
                    }
                ],
                "menu":"音乐管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
